<?php
use CRM_Eventmanagelocations_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Manage_Event_Locations',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Manage_Event_Locations',
        'label' => E::ts('Manage Event Locations'),
        'api_entity' => 'Address',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'street_address',
            'supplemental_address_1',
            'supplemental_address_2',
            'supplemental_address_3',
            'city',
            'postal_code',
            'country_id:label',
            'state_province_id:label',
            'county_id:label',
            'Address_LocBlock_address_id_01.email_id.email',
            'Address_LocBlock_address_id_01.email_2_id.email',
            'Address_LocBlock_address_id_01.phone_id.phone',
            'Address_LocBlock_address_id_01.phone_2_id.phone',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [
            [
              'LocBlock AS Address_LocBlock_address_id_01',
              'INNER',
              [
                'id',
                '=',
                'Address_LocBlock_address_id_01.address_id',
              ],
            ],
          ],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_Manage_Event_Locations_SearchDisplay_Manage_Event_Locations_Table_1',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Manage_Event_Locations_Table_1',
        'label' => E::ts('Manage Event Locations'),
        'saved_search_id.name' => 'Manage_Event_Locations',
        'type' => 'table',
        'settings' => [
          'description' => E::ts(NULL),
          'sort' => [],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'street_address',
              'dataType' => 'String',
              'label' => E::ts('Street Address'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'supplemental_address_1',
              'dataType' => 'String',
              'label' => E::ts('Supplemental Address 1'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'supplemental_address_2',
              'dataType' => 'String',
              'label' => E::ts('Supplemental Address 2'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'supplemental_address_3',
              'dataType' => 'String',
              'label' => E::ts('Supplemental Address 3'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'city',
              'dataType' => 'String',
              'label' => E::ts('City'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'postal_code',
              'dataType' => 'String',
              'label' => E::ts('Post Code'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'country_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Country'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'state_province_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('State/Territory'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'county_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Shire'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'Address_LocBlock_address_id_01.email_id.email',
              'dataType' => 'String',
              'label' => E::ts('Email'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'Address_LocBlock_address_id_01.email_2_id.email',
              'dataType' => 'String',
              'label' => E::ts('Email 2'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'Address_LocBlock_address_id_01.phone_id.phone',
              'dataType' => 'String',
              'label' => E::ts('Phone'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'Address_LocBlock_address_id_01.phone_2_id.phone',
              'dataType' => 'String',
              'label' => E::ts('Phone 2'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'text' => E::ts(''),
              'style' => 'default',
              'size' => 'btn-xs',
              'icon' => 'fa-bars',
              'links' => [
                [
                  'path' => '',
                  'icon' => 'fa-save',
                  'text' => E::ts('Update'),
                  'style' => 'default',
                  'conditions' => [],
                  'task' => 'update',
                  'entity' => 'Address',
                  'action' => '',
                  'join' => '',
                  'target' => 'crm-popup',
                ],
                [
                  'task' => 'delete',
                  'entity' => 'Address',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => E::ts('Delete'),
                  'style' => 'danger',
                  'path' => '',
                  'action' => '',
                  'conditions' => [],
                ],
              ],
              'type' => 'menu',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => TRUE,
          'classes' => ['table', 'table-striped'],
          'actions_display_mode' => 'menu',
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
