name: frontend tests

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch: {}

jobs:
  playwright:
    uses: agileware/ci-workflows/.github/workflows/playwright-tests.yml@main
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      EXTENSION_NAME: au.com.agileware.eventmanagelocations
      SETUP_SCRIPT: tests/playwright/fixtures/setup-environment.sh
